name: Build KImageFormats
on:
  push:
    branches: [master, nerix-adjustments]
  workflow_dispatch:
  pull_request:
    branches: [master, nerix-adjustments]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2019
            vers: "6.7.3"
            forceWin32: "false"
            arch: "win64_msvc2019_64"
          - os: macos-13
            vers: "6.7.3"
            universalBinary: "true"

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
          version: ${{ matrix.vers }}
          arch: ${{ matrix.arch }}

      # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: "7eb700c9688daed6d8bdcdc571ebe3eedea6a774"

      - name: Build KImageFormats (just one big step for now)
        run: pwsh pwsh/buildkimageformats.ps1
        env:
          buildArch: ${{ matrix.buildArch }}

      - name: "Upload Artifact"
        if: github.ref != 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: kimageformats-${{ matrix.os }}-${{ matrix.vers }}${{ matrix.arch && format('-{0}', matrix.arch) || '' }}
          path: kimageformats/output

      - name: "Zip Artifact"
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: "zip"
          path: kimageformats/output/
          filename: "kimageformats-${{ matrix.os }}-${{ matrix.vers }}${{ matrix.arch && format('-{0}', matrix.arch) || '' }}.zip"

      - name: "Upload to continous release"
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "cont"
          files: kimageformats-*.zip
